
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Componentes.*;
import Encomenda.*;
import Dados.*;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author pedrogoncalves
 */
public class Extras extends javax.swing.JFrame {
    
    private BaseDados bd;
    private Map<Integer,Peca> pecas;
    private static Encomenda pack;
    int p1=0,p2=0,p3=0,p4=0,p5=0,p6=0,p7=0,p8=0,p9=0,p10=0,p11=0,p12=0,p13=0,p14=0,p15=0,p16=0,p17=0,p18=0,p19=0,p20=0,p21=0,p22=0,p23=0,p24=0,p25=0; 
    
    
    /**
     * Creates new form Extras
     */
    public Extras() {
        initComponents();
    }
    
    public Extras(Encomenda e)
    {
        bd = new BaseDados();
        pecas = bd.getTodasPecas();
        pack = new Encomenda(e);
        initComponents();
    }
    
    public Extras(Encomenda e,String pac)
    {
        bd = new BaseDados();
        pecas = bd.getTodasPecas();
        pack = new Encomenda(e);
        initComponents();
        
        if(pac.equals("Pacote Conforto"))
        {
            
            pp1.setSelected(true);
            pp4.setSelected(true);
            pp6.setSelected(true);
            pp9.setSelected(true);
            pp13.setSelected(true);
            pp22.setSelected(true);
            pp23.setSelected(true);
            pp25.setSelected(true);
            p1=1;p4=1;p6=1;p9=1;p13=1;p22=1;p23=1;p25=1;
        }
        
        if(pac.equals("Pacote Sport"))
        {
            pp3.setSelected(true);
            pp7.setSelected(true);
            pp10.setSelected(true);
            pp14.setSelected(true);
            pp21.setSelected(true);
            pp24.setSelected(true);
            pp5.setSelected(true);
            p3=1;p7=1;p10=1;p14=1;p21=1;p24=1;p5=1;
        }
        if(pac.equals("Pacote Executivo"))
        {
            pp2.setSelected(true);
            pp4.setSelected(true);
            pp8.setSelected(true);
            pp12.setSelected(true);
            pp14.setSelected(true);
            pp15.setSelected(true);
            pp17.setSelected(true);
            pp16.setSelected(true);
            pp18.setSelected(true);
            pp19.setSelected(true);
            pp20.setSelected(true);
            pp24.setSelected(true);
            pp25.setSelected(true);
            p2=1;p4=1;p8=1;p12=1;p14=1;p15=1;p17=1;p16=1;p18=1;p19=1;p20=1;p24=1;p25=1;
        }
    }
    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Proximo = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        pp1 = new javax.swing.JCheckBox();
        pp2 = new javax.swing.JCheckBox();
        pp4 = new javax.swing.JCheckBox();
        pp5 = new javax.swing.JCheckBox();
        pp6 = new javax.swing.JCheckBox();
        pp8 = new javax.swing.JCheckBox();
        pp9 = new javax.swing.JCheckBox();
        pp10 = new javax.swing.JCheckBox();
        pp12 = new javax.swing.JCheckBox();
        pp13 = new javax.swing.JCheckBox();
        pp14 = new javax.swing.JCheckBox();
        pp16 = new javax.swing.JCheckBox();
        pp17 = new javax.swing.JCheckBox();
        pp18 = new javax.swing.JCheckBox();
        pp20 = new javax.swing.JCheckBox();
        pp21 = new javax.swing.JCheckBox();
        pp22 = new javax.swing.JCheckBox();
        pp24 = new javax.swing.JCheckBox();
        pp3 = new javax.swing.JCheckBox();
        pp7 = new javax.swing.JCheckBox();
        pp11 = new javax.swing.JCheckBox();
        pp15 = new javax.swing.JCheckBox();
        pp19 = new javax.swing.JCheckBox();
        pp23 = new javax.swing.JCheckBox();
        pp25 = new javax.swing.JCheckBox();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Proximo.setText("Próximo");
        Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximoActionPerformed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        pp1.setText("Jante Liga Leve 16");
        pp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp1ActionPerformed(evt);
            }
        });

        pp2.setText("Jante Liga Leve 17");
        pp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp2ActionPerformed(evt);
            }
        });

        pp4.setText("Estofo Clássico");
        pp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp4ActionPerformed(evt);
            }
        });

        pp5.setText("Estofo Desportivo");
        pp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp5ActionPerformed(evt);
            }
        });

        pp6.setText("AI Claro");
        pp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp6ActionPerformed(evt);
            }
        });

        pp8.setText("Forro em Pele");
        pp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp8ActionPerformed(evt);
            }
        });

        pp9.setText("Forro em Pano");
        pp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp9ActionPerformed(evt);
            }
        });

        pp10.setText("Forro em Alcântara");
        pp10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp10ActionPerformed(evt);
            }
        });

        pp12.setText("Faróis Laser");
        pp12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp12ActionPerformed(evt);
            }
        });

        pp13.setText("Vidro Normal");
        pp13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp13ActionPerformed(evt);
            }
        });

        pp14.setText("Vidro Escurecido");
        pp14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp14ActionPerformed(evt);
            }
        });

        pp16.setText("GPS");
        pp16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp16ActionPerformed(evt);
            }
        });

        pp17.setText("Ecrâ de Bordo");
        pp17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp17ActionPerformed(evt);
            }
        });

        pp18.setText("Câmara Traseira");
        pp18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp18ActionPerformed(evt);
            }
        });

        pp20.setText("Suspensão Normal");
        pp20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp20ActionPerformed(evt);
            }
        });

        pp21.setText("Suspensão Adaptativa");
        pp21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp21ActionPerformed(evt);
            }
        });

        pp22.setText("Suspensão Pneumática");
        pp22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp22ActionPerformed(evt);
            }
        });

        pp24.setText("Pneu Runflat");
        pp24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp24ActionPerformed(evt);
            }
        });

        pp3.setText("Jante Carbono 18");
        pp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp3ActionPerformed(evt);
            }
        });

        pp7.setText("AI Escuro");
        pp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp7ActionPerformed(evt);
            }
        });

        pp11.setText("Faróis LED");
        pp11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp11ActionPerformed(evt);
            }
        });

        pp15.setText("AC");
        pp15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp15ActionPerformed(evt);
            }
        });

        pp19.setText("Câmara Dianteira");
        pp19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp19ActionPerformed(evt);
            }
        });

        pp23.setText("Pneu Normal");
        pp23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp23ActionPerformed(evt);
            }
        });

        pp25.setText("Sensor de Estacionamento");
        pp25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pp25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pp1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pp2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pp3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pp8)
                            .addComponent(pp4)
                            .addComponent(pp12)
                            .addComponent(pp16))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pp5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pp6)
                                        .addGap(71, 71, 71))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pp9)
                                            .addComponent(pp13))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pp14)
                                            .addComponent(pp10)
                                            .addComponent(pp18))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(pp11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(pp7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(pp19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(pp20))
                                            .addComponent(pp15)))))
                            .addComponent(pp25))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(error)
                                .addGap(193, 193, 193)
                                .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Proximo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pp17)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pp21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pp22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pp23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pp24)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pp1)
                    .addComponent(pp2)
                    .addComponent(pp4)
                    .addComponent(pp3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pp6)
                    .addComponent(pp7)
                    .addComponent(pp8)
                    .addComponent(pp5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pp10)
                    .addComponent(pp11)
                    .addComponent(pp12)
                    .addComponent(pp9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pp13)
                    .addComponent(pp14)
                    .addComponent(pp15)
                    .addComponent(pp16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pp17)
                    .addComponent(pp18)
                    .addComponent(pp19)
                    .addComponent(pp20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pp21)
                    .addComponent(pp22)
                    .addComponent(pp23)
                    .addComponent(pp24))
                .addGap(18, 18, 18)
                .addComponent(pp25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proximo)
                    .addComponent(Voltar)
                    .addComponent(error))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarActionPerformed

    private void ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximoActionPerformed
        String[] args = new String[0];
        List<Peca> in = new ArrayList<>();
        
        
        if(p1 == 1)
            in.add(pecas.get(1));
        if(p2 == 1)
            in.add(pecas.get(2));
        if(p3 == 1)
            in.add(pecas.get(3));
        if(p4 == 1)
            in.add(pecas.get(4));
        if(p5 == 1)
            in.add(pecas.get(5));
        if(p6 == 1)
            in.add(pecas.get(6));
        if(p7 == 1)
            in.add(pecas.get(7));
        if(p8 == 1)
            in.add(pecas.get(8));
        if(p9 == 1)
            in.add(pecas.get(9));
        if(p10 == 1)
            in.add(pecas.get(10));
        if(p11 == 1)
            in.add(pecas.get(11));
        if(p12 == 1)
            in.add(pecas.get(12));
        if(p13 == 1)
            in.add(pecas.get(13));
        if(p14 == 1)
            in.add(pecas.get(14));
        if(p15 == 1)
            in.add(pecas.get(15));
        if(p16 == 1)
            in.add(pecas.get(16));
        if(p17 == 1)
            in.add(pecas.get(17));
        if(p18 == 1)
            in.add(pecas.get(18));
        if(p19 == 1)
            in.add(pecas.get(19));
        if(p20 == 1)
            in.add(pecas.get(20));
        if(p21 == 1)
            in.add(pecas.get(21));
        if(p22 == 1)
            in.add(pecas.get(22));
        if(p23 == 1)
            in.add(pecas.get(23));
        if(p24 == 1)
            in.add(pecas.get(24));
        if(p25 == 1)
            in.add(pecas.get(25));
        
        pack.setPecas(in);
        
        if(!pack.colisoes())
        {
            
            if(!pack.missing())
            {
                double pc = pack.calculaPreco();
                pack.setPreco(pc);
                int size = bd.getNEnc();
                size+=1;
                pack.setId(size);
                pack.setEstado(1);
                pack.setDesconto(0);
                Encomendar x = new Encomendar(pack);
                x.main(args); 
            }
            else
            {
                error.setText("Existem dependencias de peças não satisfeitas!");
                error.setForeground(Color.RED);
            }
        }
        else
        {
            error.setText("Peças incompativeis selecionadas!");
            error.setForeground(Color.RED);
        }
            
        // TODO add your handling code here:
    }//GEN-LAST:event_ProximoActionPerformed

    private void pp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp1ActionPerformed
        // TODO add your handling code here:
        if(p1 == 0)
            p1 = 1;
        else 
            p1 = 0;
    }//GEN-LAST:event_pp1ActionPerformed

    private void pp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp3ActionPerformed
        // TODO add your handling code here:
        if(p3 == 0)
            p3 = 1;
        else 
            p3 = 0;
    }//GEN-LAST:event_pp3ActionPerformed

    private void pp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp6ActionPerformed
        // TODO add your handling code here:
        if(p6 == 0)
            p6 = 1;
        else 
            p6 = 0;
    }//GEN-LAST:event_pp6ActionPerformed

    private void pp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp8ActionPerformed
        // TODO add your handling code here:
        if(p8 == 0)
            p8 = 1;
        else 
            p8 = 0;
    }//GEN-LAST:event_pp8ActionPerformed

    private void pp10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp10ActionPerformed
        // TODO add your handling code here:
        if(p10 == 0)
            p10 = 1;
        else 
            p10 = 0;
    }//GEN-LAST:event_pp10ActionPerformed

    private void pp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp5ActionPerformed
        // TODO add your handling code here:
        if(p5 == 0)
            p5 = 1;
        else 
            p5 = 0;
    }//GEN-LAST:event_pp5ActionPerformed

    private void pp11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp11ActionPerformed
        // TODO add your handling code here:
        if(p11 == 0)
            p11 = 1;
        else 
            p11 = 0;
    }//GEN-LAST:event_pp11ActionPerformed

    private void pp14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp14ActionPerformed
        // TODO add your handling code here:
        if(p14 == 0)
            p14 = 1;
        else 
            p14 = 0;
    }//GEN-LAST:event_pp14ActionPerformed

    private void pp20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp20ActionPerformed
        // TODO add your handling code here:
        if(p20 == 0)
            p20 = 1;
        else 
            p20 = 0;
    }//GEN-LAST:event_pp20ActionPerformed

    private void pp24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp24ActionPerformed
        // TODO add your handling code here:
        if(p24 == 0)
            p24 = 1;
        else 
            p24 = 0;
    }//GEN-LAST:event_pp24ActionPerformed

    private void pp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp2ActionPerformed
        // TODO add your handling code here:
        if(p2 == 0)
            p2 = 1;
        else 
            p2 = 0;
    }//GEN-LAST:event_pp2ActionPerformed

    private void pp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp4ActionPerformed
        // TODO add your handling code here:
        if(p4 == 0)
            p4 = 1;
        else 
            p4 = 0;
    }//GEN-LAST:event_pp4ActionPerformed

    private void pp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp7ActionPerformed
        // TODO add your handling code here:
        if(p7 == 0)
            p7 = 1;
        else 
            p7 = 0;
    }//GEN-LAST:event_pp7ActionPerformed

    private void pp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp9ActionPerformed
        // TODO add your handling code here:
        if(p9 == 0)
            p9 = 1;
        else 
            p9 = 0;
    }//GEN-LAST:event_pp9ActionPerformed

    private void pp12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp12ActionPerformed
        // TODO add your handling code here:
        if(p12 == 0)
            p12 = 1;
        else 
            p12 = 0;
    }//GEN-LAST:event_pp12ActionPerformed

    private void pp13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp13ActionPerformed
        // TODO add your handling code here:
        if(p13 == 0)
            p13 = 1;
        else 
            p13 = 0;
    }//GEN-LAST:event_pp13ActionPerformed

    private void pp15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp15ActionPerformed
        // TODO add your handling code here:
        if(p15 == 0)
            p15 = 1;
        else 
            p15 = 0;
    }//GEN-LAST:event_pp15ActionPerformed

    private void pp16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp16ActionPerformed
        // TODO add your handling code here:
        if(p16 == 0)
            p16 = 1;
        else 
            p16 = 0;
    }//GEN-LAST:event_pp16ActionPerformed

    private void pp17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp17ActionPerformed
        // TODO add your handling code here:
        if(p17 == 0)
            p17 = 1;
        else 
            p17 = 0;
    }//GEN-LAST:event_pp17ActionPerformed

    private void pp18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp18ActionPerformed
        // TODO add your handling code here:
        if(p18 == 0)
            p18 = 1;
        else 
            p18 = 0;
    }//GEN-LAST:event_pp18ActionPerformed

    private void pp19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp19ActionPerformed
        // TODO add your handling code here:
        if(p19 == 0)
            p19 = 1;
        else 
            p19 = 0;
    }//GEN-LAST:event_pp19ActionPerformed

    private void pp21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp21ActionPerformed
        // TODO add your handling code here:
        if(p21 == 0)
            p21 = 1;
        else 
            p21 = 0;
    }//GEN-LAST:event_pp21ActionPerformed

    private void pp22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp22ActionPerformed
        // TODO add your handling code here:
        if(p22 == 0)
            p22 = 1;
        else 
            p22 = 0;
    }//GEN-LAST:event_pp22ActionPerformed

    private void pp23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp23ActionPerformed
        // TODO add your handling code here:
        if(p23 == 0)
            p23 = 1;
        else 
            p23 = 0;
    }//GEN-LAST:event_pp23ActionPerformed

    private void pp25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pp25ActionPerformed
        // TODO add your handling code here:
        if(p25 == 0)
            p25 = 1;
        else 
            p25 = 0;
    }//GEN-LAST:event_pp25ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Encomenda send = pack;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Extras(send,args[0]).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Proximo;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel error;
    private javax.swing.JCheckBox pp1;
    private javax.swing.JCheckBox pp10;
    private javax.swing.JCheckBox pp11;
    private javax.swing.JCheckBox pp12;
    private javax.swing.JCheckBox pp13;
    private javax.swing.JCheckBox pp14;
    private javax.swing.JCheckBox pp15;
    private javax.swing.JCheckBox pp16;
    private javax.swing.JCheckBox pp17;
    private javax.swing.JCheckBox pp18;
    private javax.swing.JCheckBox pp19;
    private javax.swing.JCheckBox pp2;
    private javax.swing.JCheckBox pp20;
    private javax.swing.JCheckBox pp21;
    private javax.swing.JCheckBox pp22;
    private javax.swing.JCheckBox pp23;
    private javax.swing.JCheckBox pp24;
    private javax.swing.JCheckBox pp25;
    private javax.swing.JCheckBox pp3;
    private javax.swing.JCheckBox pp4;
    private javax.swing.JCheckBox pp5;
    private javax.swing.JCheckBox pp6;
    private javax.swing.JCheckBox pp7;
    private javax.swing.JCheckBox pp8;
    private javax.swing.JCheckBox pp9;
    // End of variables declaration//GEN-END:variables
}
