/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Dados.*;
import Encomenda.*;
import Componentes.*;
import java.time.LocalDateTime;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author pedrogoncalves
 */
public class Modelo extends javax.swing.JFrame {

    private BaseDados bd;
    private InfoPacote ip;
    private String goM;
    
    /**
     * Creates new form Modelo
     */
    public Modelo() {
        bd = new BaseDados();
        ip = new InfoPacote();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Voltar = new javax.swing.JButton();
        Proximo = new javax.swing.JButton();
        Label_Marca = new javax.swing.JLabel();
        Label_Modelo = new javax.swing.JLabel();
        Label_Motorização = new javax.swing.JLabel();
        Label_Cor = new javax.swing.JLabel();
        Label_Pacote = new javax.swing.JLabel();
        String[] kk = bd.getMotorizacoes("Biat", "BZ1");
        Motorizaçao = new javax.swing.JComboBox<>(kk);
        String[] bb = bd.getModelo("Biat");
        Modelo = new javax.swing.JComboBox<>();
        String[] give5 = bd.getMarca();
        Marca = new javax.swing.JComboBox<>();
        String[] give3 = bd.getCores();
        Cor = new javax.swing.JComboBox<>(give3);
        String[] give2 = bd.getPacotes();
        Pacote = new javax.swing.JComboBox<>(give2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Proximo.setText("Próximo");
        Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximoActionPerformed(evt);
            }
        });

        Label_Marca.setText("Marca:");

        Label_Modelo.setText("Modelo:");

        Label_Motorização.setText("Motorização:");

        Label_Cor.setText("Cor:");

        Label_Pacote.setText("Pacote:");

        Motorizaçao.setModel(new javax.swing.DefaultComboBoxModel<>(kk));

        Modelo.setModel(new javax.swing.DefaultComboBoxModel<>(bb));
        Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloActionPerformed(evt);
            }
        });

        Marca.setModel(new javax.swing.DefaultComboBoxModel<>(give5));
        Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaActionPerformed(evt);
            }
        });

        Cor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preto", "Branco", "Vermelho", "Amarelo", "Cinzento", "Verde" }));

        Pacote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem Pacote", "Pacote Conforto", "Pacote Sport", "Pacote Executivo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Modelo)
                            .addComponent(Label_Marca)
                            .addComponent(Label_Cor)
                            .addComponent(Label_Pacote))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label_Motorização)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Modelo, 0, 150, Short.MAX_VALUE)
                    .addComponent(Marca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Motorizaçao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pacote, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Marca)
                    .addComponent(Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Modelo)
                    .addComponent(Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Motorização)
                    .addComponent(Motorizaçao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Cor)
                    .addComponent(Cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Pacote)
                    .addComponent(Pacote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Voltar)
                    .addComponent(Proximo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_VoltarActionPerformed

    private void ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximoActionPerformed
        Carro novo = new Carro(Modelo.getSelectedItem().toString(),Motorizaçao.getSelectedItem().toString(),Cor.getSelectedItem().toString(),Marca.getSelectedItem().toString());
        Encomenda next = new Encomenda();
        next.setCarro(novo);
        String[] args = new String[1];
        if(Pacote.getSelectedItem().toString().equals("Sem Pacote"))
        {
            next.setPacote(null);
            args[0] = "Sem Pacote";
        }
        if(Pacote.getSelectedItem().toString().equals("Pacote Conforto"))
        {
            next.setPacote(ip.getConforto());
            args[0] = "Pacote Conforto";
        }
        if(Pacote.getSelectedItem().toString().equals("Pacote Sport"))
        {
            next.setPacote(ip.getSport());
            args[0] = "Pacote Sport";
        }
        if(Pacote.getSelectedItem().toString().equals("Pacote Executivo"))
        {
            next.setPacote(ip.getExecutivo());
             args[0] = "Pacote Executivo";
        }
        next.setData(LocalDateTime.now());
        //next.setPacote(Pacote.getSelectedItem().toString());
        Extras x = new Extras();
        x.main(args);
        // TODO add your handling code here:
    }//GEN-LAST:event_ProximoActionPerformed

    private void MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaActionPerformed
        // TODO add your handling code here:
        String mrc = Marca.getSelectedItem().toString();
        String[] give = bd.getModelo(mrc);
        DefaultComboBoxModel model = new DefaultComboBoxModel(give);
        Modelo.setModel(model);
        String mdl = Modelo.getSelectedItem().toString();
        String[] give2 = bd.getMotorizacoes(mrc, mdl);
        DefaultComboBoxModel model2 = new DefaultComboBoxModel(give2);
        Motorizaçao.setModel(model2);
    }//GEN-LAST:event_MarcaActionPerformed

    private void ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloActionPerformed
        // TODO add your handling code here:
        String mrc = Marca.getSelectedItem().toString();
        String mdl = Modelo.getSelectedItem().toString();
        String[] give = bd.getMotorizacoes(mrc, mdl);
        DefaultComboBoxModel model = new DefaultComboBoxModel(give);
        Motorizaçao.setModel(model);
    }//GEN-LAST:event_ModeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cor;
    private javax.swing.JLabel Label_Cor;
    private javax.swing.JLabel Label_Marca;
    private javax.swing.JLabel Label_Modelo;
    private javax.swing.JLabel Label_Motorização;
    private javax.swing.JLabel Label_Pacote;
    private javax.swing.JComboBox<String> Marca;
    private javax.swing.JComboBox<String> Modelo;
    private javax.swing.JComboBox<String> Motorizaçao;
    private javax.swing.JComboBox<String> Pacote;
    private javax.swing.JButton Proximo;
    private javax.swing.JButton Voltar;
    // End of variables declaration//GEN-END:variables
}
